[versions]
shadow = "8.3.9"
jetbrains-annotations = "23.0.0"
via-nbt = "5.1.2"
fast-util = "8.5.17"
gson = "2.8.9"
java-diff-utils = "4.12"
mod-publish = "1.0.0"

[libraries]
shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
via-nbt = { group = "com.viaversion", name = "nbt", version.ref = "via-nbt" }
fast-util = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fast-util" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
java-diff-utils = { group = "io.github.java-diff-utils", name = "java-diff-utils", version.ref = "java-diff-utils" }
mod-publish = { group = "me.modmuss50", name = "mod-publish-plugin", version.ref = "mod-publish" }
