name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload build artifacts api
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: build/libs/packetevents-api-*.jar

      - name: Upload build artifacts spigot
        uses: actions/upload-artifact@v4
        with:
          name: spigot-build
          path: build/libs/packetevents-spigot-*.jar

      - name: Upload build artifacts netty-common
        uses: actions/upload-artifact@v4
        with:
          name: netty-common-build
          path: build/libs/packetevents-netty-common-*.jar

      - name: Upload build artifacts bungeecord
        uses: actions/upload-artifact@v4
        with:
          name: bungeecord-build
          path: build/libs/packetevents-bungeecord-*.jar

      - name: Upload build artifacts velocity
        uses: actions/upload-artifact@v4
        with:
          name: velocity-build
          path: build/libs/packetevents-velocity-*.jar

      - name: Upload build artifacts fabric
        uses: actions/upload-artifact@v4
        with:
          name: fabric-build
          path: build/libs/packetevents-fabric-*.jar

      - name: Upload build artifacts sponge
        uses: actions/upload-artifact@v4
        with:
          name: sponge-build
          path: build/libs/packetevents-sponge-*.jar
